version: "3.8"

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 5m
      max-file: "2"

services:
  ubuntu:
    init: true
    container_name: ssh_container
    build: 
      context: .
      dockerfile: Dockerfile
    <<: *logging
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
    restart: on-failure
    